# Module
from datetime import date
import os
import time
import random
import platform
import psutil

# nur nutzen, wenn man den bildschirm löschen will: os.system('cls' if os.name == 'nt' else 'clear')

# Variablen
today = date.today()
crash = random.randint(0,100)
architecture = platform.machine()
ops = "MarcellD'AvisOS"
version = "0.2A"
cpu = platform.processor()
ram_total = psutil.virtual_memory().total / (1024 ** 3)
esc_pressed = False

# BootUp
os.system('cls' if os.name == 'nt' else 'clear')
print("M   M   A   RRRR   CCC  EEEEE L     L")
print("MM MM  A A  R   R C   C E     L     L")
print("M M M A   A R   R C     E     L     L")
print("M   M A   A RRRR  C     EEEEE L     L")
print("M   M AAAAA R R   C     E     L     L")
print("M   M A   A R  R  C   C E     L     L")
print("M   M A   A R   R  CCC  EEEEE LLLLL LLLLL")
print(" ")
print("   DDD    AA     A   V   V  III   SSSS")
print("   D  D    A    A A  V   V   I   S    ")
print("   D   D  A    A   A V   V   I   S    ")
print("   D   D       A   A V   V   I    SSS ")
print("   D   D       AAAAA  V V    I       S")
print("   D  D        A   A  V V    I       S")
print("   DDD         A   A   V    III  SSSS")
print("")
print("                OOO   SSSS")
print("               O   O S    ")
print("               O   O S    ")
print("               O   O  SSS ")
print("               O   O     S")
print("               O   O     S")
print("                OOO  SSSS")
print("----------------------------------------")
print("MarcellD'AvisOS startet...         V0.2A")
time.sleep(5)

# crash
if crash < 10:
    os.system('cls' if os.name == 'nt' else 'clear')
    time.sleep(1)
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    time.sleep(1)
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    time.sleep(1)
    print("&&&      &&&&      &&&&      &&&&")
    print("&&&&&*   &&&   &&   &&&&&&   &&&&")
    time.sleep(1)
    print("&&&&&*   &&&        &&&&&&   &&&&")
    print("&&&&&*   &&&&&    #&&&&&&&   &&&&")
    time.sleep(1)
    print("&&&&&*   &&&      &&   &&&   &&&&")
    time.sleep(1)
    print("&&&&&*   &&   &&=      &&&   &&&&")
    print("&&&&&*   &&   &&&&    &&&&   &&&&")
    time.sleep(1)
    print("&&&&&*   &&           +&&&   &&&&")
    print("&&&&&&&&&&&&&&    &&&&&&&&&&&&&&&")
    time.sleep(1)
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    time.sleep(1)
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    time.sleep(1)
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    time.sleep(1)
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    time.sleep(1)
    print("Ihr PC enthält keine 1&1 zertifizierte Produkte. Bitte ändern sie das. Arschloch")
    time.sleep(1)
    print("ERR_KERNEL_PANIC")
    os.system('shutdown -f' if os.name == 'nt' else 'systemctl poweroff')#

os.system('cls' if os.name == 'nt' else 'clear')
while True:
        
        # Terminal
        action = input("MarcellD'AvisTerminal: ")

        # Term Version
        if action == "über:term":
            print("TTTTT EEEEE RRRR  M   M III N   N   A   L    ")
            print("  T   E     R   R MM MM  I  N   N  A A  L    ")
            print("  T   E     R   R M M M  I  NN  N A   A L    ")
            print("  T   EEEE  RRRR  M   M  I  N N N A   A L    ")
            print("  T   E     R R   M   M  I  N  NN AAAAA L    ")
            print("  T   E     R  R  M   M  I  N   N A   A L    ")
            print("  T   EEEEE R   R M   M III N   N A   A LLLLL")
            print("---------------------------------------------")
            print("MarcellD'Avis Terminal                  V0.2A")
            print("          (C) Copyright 2025 kyr3xx")

        # PC Info
        if action == "über:mdos":
            while esc_pressed == False:
                time.sleep(1)
                print("+X+;Xxx$$&x;$$$$X;&$$XXX$&$&x;x+X&&&&&&&&&&&&&&&&&")
                print("xxXX$x;+$$X:x&X$$xx$$X&&&&&&&&&&X&&&&&&&&&&&&&&&&&")
                time.sleep(1)
                print("$.+$&X+x$$$X$$$X$$$X&&&&&&$$&&&&&&&&&&&&&&&&&&&&&&")
                time.sleep(1)
                print("x&$X$xx$$$$X+xxxxx&&&&$+;;;+;xxX$&&&&&&&&&&&&&&&&&")
                print("xxXxX+X$$X$XXxxxx$&&X+;:::::;;+xxXX&&&&&&&&&&&&&&&")
                print("xxxxxxxxxxxxxxxxX&&;;:::.....::;;;+X&&&&&&&&&&&&&&")
                time.sleep(1)
                print("XXXXXXXXXXXXXXXX&&x::::.......:;:;;+X$&&&&&&&&&&&&")
                time.sleep(1)
                print("xxXXxxxXXXXXxxx&&$;;::...........::;x&&&&&&&&&&&&&")
                print("+xxxxxxxXXXx++;&&;;:::............:;x$&&&&&&&&&&&&")
                print(";+xxxxxxxXXx+:.;X:::+;;;.........:;;+&XX$XXXXXXX$$")
                print(";+++++++xxxxx:;$;:..:;..:;.......::+x::...        ")
                time.sleep(1)
                print("::...        ..+;:.....:++;..;XX+x$x.  .  ...  .::")
                print("  ...  ..   x&;;;:.......::.+;.;;&++....:..:.:.:;;")
                time.sleep(1)
                print(".:  ;&&&&&&&& &x;;:.....::::+....:;X:...:.::.::;+:")
                time.sleep(1)
                print("&&&&&&&&&&&&; +x;:::::::...:+;...:x   ..  .:.. .;+")
                print("&&&&&&&&&&&&: :x;;::;:::;;.:X+;;;x&&&&&X..:::;:;;+")
                print("&&&&&&&&&&&&x .:x;;::::;x+xXXx+:+&&&&&&&&&&;;.:;;+")
                time.sleep(1)
                print("&&&&&&&&&&&&&  ;:;x::::;;;;+::+x&&&&&&&&&&&&&&:.;;")
                time.sleep(1)
                print("&&&&&&&&&&&&&   ::;X:...::;+X&&&&&&&&&&&&&&&&&&;;:")
                print("&&&&&&&&&&&&&    :::;Xx;+$&  &&&&&&&&&&&&&&&&&&x$X")
                print("&&&&&&&&&&&&&+    ;:;;;;:$  x&&&&&&&&&&&&&&&&&xX+$")
                time.sleep(1)
                print("&&&&&&&&&&&&&&     x::::x  +&&&&&&&&&&&&&&&&&&.:.;")
                print("&&&&&&&&&&&&&&      xx$   :&&&&&&&&&&&&&&&&&&&&;::")
                time.sleep(1)
                print("&&&&&&&&&&&&&&;           ;&&&&&&&&&&&&&&&&&&&&;;;")
                print("&&&&&&&&&&&&&&&            &&&&&&&&&&&&&&&&&&&&&&&")
                time.sleep(1)
                print("&&&&&&&&&&&&&&&            &&&&&&&&&&&&&&&&&&&&&&&")
                print("&&&&&&&&&&&&&&&            &&&&&&&&&&&&&&&&&&&&&$$")
                print("--------------------------------------------------")
                print("OS: " + ops)
                print("Version: " + version)
                print("CPU: " + cpu)
                print("Architektur: " + architecture)
                print("RAM: " + str(ram_total) + "GB")
                break
        
        # Herunterfahren
        if action == "herunterfahren":
            os.system('cls' if os.name == 'nt' else 'clear')
            print("M   M   A   RRRR   CCC  EEEEE L     L")
            print("MM MM  A A  R   R C   C E     L     L")
            print("M M M A   A R   R C     E     L     L")
            print("M   M A   A RRRR  C     EEEEE L     L")
            print("M   M AAAAA R R   C     E     L     L")
            print("M   M A   A R  R  C   C E     L     L")
            print("M   M A   A R   R  CCC  EEEEE LLLLL LLLLL")
            print(" ")
            print("   DDD    AA     A   V   V  III   SSSS")
            print("   D  D    A    A A  V   V   I   S    ")
            print("   D   D  A    A   A V   V   I   S    ")
            print("   D   D       A   A V   V   I    SSS ")
            print("   D   D       AAAAA  V V    I       S")
            print("   D  D        A   A  V V    I       S")
            print("   DDD         A   A   V    III  SSSS")
            print("")
            print("                OOO   SSSS")
            print("               O   O S    ")
            print("               O   O S    ")
            print("               O   O  SSS ")
            print("               O   O     S")
            print("               O   O     S")
            print("                OOO  SSSS")
            print("----------------------------------------")
            print("MarcellD'AvisOS fährt herunter...  V0.2A")
            time.sleep(5)
            os.system('cls' if os.name == 'nt' else 'clear')
            print("Danke, dass sie MarcellD'AvisOS genutzt haben. Bis später.")
            os.system('shutdown -f' if os.name == 'nt' else 'systemctl poweroff')

        # help
        if action == "hilfe":
            print("            H   H III L     FFFFF EEEEE")
            print("            H   H  I  L     F     E    ")
            print("            H   H  I  L     F     E    ")
            print("            HHHHH  I  L     FFFF  EEEE ")
            print("            H   H  I  L     F     E    ")
            print("            H   H  I  L     F     E    ")
            print("            H   H III LLLLL F     EEEEE")
            print("----------------------------------------------------")
            print("über:term..................Zeigt Infos über Terminal")
            print("über:mdos...........Zeigt Infos über MarcellD'AvisOS")
            print("herunterfahren........Fährt MarcellD'AvisOS herunter")
            print("verbinden:google.com..Verbindet den PC an google.com")
            print("nichtgut.................Zeigt einen Crash-Screen an")

        # Google
        if action == "verbinden:google.com":
            while esc_pressed == False:
                print("Verbunden an Modem via: Parallel")
                time.sleep(1)
                print("Verbinden an google.com")
                time.sleep(4)
                print("Sendet Daten an google.com")
                time.sleep(5)
                print("Erhält Daten von google.com")
                time.sleep(3)
                os.system('cls' if os.name == 'nt' else 'clear')
                print("................................................................................")
                print("‖                                                                              ‖")
                print("‖                                                                              ‖")
                print("‖              Willkommen, ANONYM. Heute ist der... Keine Ahnung!              ‖")
                print("‖                                                                              ‖")
                print("‖                                                       ,,                     ‖")
                print("‖             .g8'''bgd                               '7MM                     ‖")
                print("‖           .dP'     'M                                 MM                     ‖")
                print("‖           dm'       '   ,pW'Wq.   ,pW'Wq.   .P'Ybmmm  MM  .gP'Ya             ‖")
                print("‖           MM           6W'   'Wb 6W'   'WB :MI  I8    MM ,M'   Yb            ‖")
                print("‖           MM.    '7MMF'8M     MB 8M     M8  WmmmP'    MM 8M''''''            ‖")
                print("‖           'Mb      MM  YA.   ,A9 YA.   ,A9 8M         MM YM.    ,            ‖")
                print("‖             ''bmmmdPY   'Ybmd9'   'Ybmd9'   YMMMMMb .JMML.'Mbmmd'            ‖")
                print("‖                                            6'     dP                         ‖")
                print("‖                         NET SUCHMASCHINE    Ybmmmd'      ALPHA               ‖")
                print("‖                                                                              ‖")
                print("‖                                                                              ‖")
                print("‖         NACHRICHTEN ╏ PROTESTE GEGEN AFD GESTARTET                           ‖")
                print("‖                     ╏ PAPST LEO XIV VERREIST IN DIE TÜRKEI                   ‖")
                print("‖                     ╏ DEUTSCHE SPENDEN WENIGER ALS IM VORJAHR (2024)         ‖")
                print("‖                     ╏ IMMER MEHR DEUTSCHE SUCHEN RAT BEI KI                  ‖")
                print("‖                                                                              ‖")
                print("................................................................................")
                selec_google = input("'Google (S)uche' oder 'Auf gut (G)lück'? Entscheide (S/G) ")
                if selec_google == "s":
                    os.system('cls' if os.name == 'nt' else 'clear')
                    print("................................................................................")
                    print("‖                                                                              ‖")
                    print("‖                                                                              ‖")
                    print("‖              Willkommen, ANONYM. Heute ist der... Keine Ahnung!              ‖")
                    print("‖                                                                              ‖")
                    print("‖                                                       ,,                     ‖")
                    print("‖             .g8'''bgd                               '7MM                     ‖")
                    print("‖           .dP'     'M                                 MM                     ‖")
                    print("‖           dm'       '   ,pW'Wq.   ,pW'Wq.   .P'Ybmmm  MM  .gP'Ya             ‖")
                    print("‖           MM           6W'   'Wb 6W'   'WB :MI  I8    MM ,M'   Yb            ‖")
                    print("‖           MM.    '7MMF'8M     MB 8M     M8  WmmmP'    MM 8M''''''            ‖")
                    print("‖           'Mb      MM  YA.   ,A9 YA.   ,A9 8M         MM YM.    ,            ‖")
                    print("‖             ''bmmmdPY   'Ybmd9'   'Ybmd9'   YMMMMMb .JMML.'Mbmmd'            ‖")
                    print("‖                                            6'     dP                         ‖")
                    print("‖                         NET SUCHMASCHINE    Ybmmmd'      ALPHA               ‖")
                    print("‖                                                                              ‖")
                    print("‖                                                                              ‖")
                    print("‖         NACHRICHTEN ╏ PROTESTE GEGEN AFD GESTARTET                           ‖")
                    print("‖                     ╏ PAPST LEO XIV VERREIST IN DIE TÜRKEI                   ‖")
                    print("‖                     ╏ DEUTSCHE SPENDEN WENIGER ALS IM VORJAHR (2024)         ‖")
                    print("‖                     ╏ IMMER MEHR DEUTSCHE SUCHEN RAT BEI KI                  ‖")
                    print("‖                                                                              ‖")
                    print("................................................................................")
                    search = input("Was willst du suchen? ")
                    if search == "Bulletin Board System":
                        os.system('cls' if os.name == 'nt' else 'clear')
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&      &&&&      &&&&      &&&&")
                        print("&&&&&*   &&&   &&   &&&&&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&&        &&&&&&   &&&&")
                        print("&&&&&*   &&&&&    #&&&&&&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&&      &&   &&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&   &&=      &&&   &&&&")
                        print("&&&&&*   &&   &&&&    &&&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&           +&&&   &&&&")
                        print("&&&&&&&&&&&&&&    &&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("Ihr Modem hat nicht mehr mit dem PC kommuniziert. Schauen sie nach, ob der Parallelanschluss locker ist.")
                        time.sleep(1)
                        print("ERR_KERNEL_PANIC")
                        os.system('shutdown -f' if os.name == 'nt' else 'systemctl poweroff')
                    elif search == "Apple II":
                        os.system('cls' if os.name == 'nt' else 'clear')
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&      &&&&      &&&&      &&&&")
                        print("&&&&&*   &&&   &&   &&&&&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&&        &&&&&&   &&&&")
                        print("&&&&&*   &&&&&    #&&&&&&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&&      &&   &&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&   &&=      &&&   &&&&")
                        print("&&&&&*   &&   &&&&    &&&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&           +&&&   &&&&")
                        print("&&&&&&&&&&&&&&    &&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("Ihr Modem hat nicht mehr mit dem PC kommuniziert. Schauen sie nach, ob der Parallelanschluss locker ist.")
                        time.sleep(1)
                        print("ERR_KERNEL_PANIC")
                        os.system('shutdown -f' if os.name == 'nt' else 'systemctl poweroff')
                    elif search == "Commodore 64":
                        os.system('cls' if os.name == 'nt' else 'clear')
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&      &&&&      &&&&      &&&&")
                        print("&&&&&*   &&&   &&   &&&&&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&&        &&&&&&   &&&&")
                        print("&&&&&*   &&&&&    #&&&&&&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&&      &&   &&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&   &&=      &&&   &&&&")
                        print("&&&&&*   &&   &&&&    &&&&   &&&&")
                        time.sleep(1)
                        print("&&&&&*   &&           +&&&   &&&&")
                        print("&&&&&&&&&&&&&&    &&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                        time.sleep(1)
                        print("Ihr Modem hat nicht mehr mit dem PC kommuniziert. Schauen sie nach, ob der Parallelanschluss locker ist.")
                        time.sleep(1)
                        print("ERR_KERNEL_PANIC")
                        os.system('shutdown -f' if os.name == 'nt' else 'systemctl poweroff')
                    else:
                        
                        os.system('cls' if os.name == 'nt' else 'clear')
                        print("................................................................................")
                        print("‖                                                                              ‖")
                        print("‖                                                                              ‖")
                        print("‖              Willkommen, ANONYM. Heute ist der... Keine Ahnung!              ‖")
                        print("‖                                                                              ‖")
                        print("‖                                                       ,,                     ‖")
                        print("‖             .g8'''bgd                               '7MM                     ‖")
                        print("‖           .dP'     'M                                 MM                     ‖")
                        print("‖           dm'       '   ,pW'Wq.   ,pW'Wq.   .P'Ybmmm  MM  .gP'Ya             ‖")
                        print("‖           MM           6W'   'Wb 6W'   'WB :MI  I8    MM ,M'   Yb            ‖")
                        print("‖           MM.    '7MMF'8M     MB 8M     M8  WmmmP'    MM 8M''''''            ‖")
                        print("‖           'Mb      MM  YA.   ,A9 YA.   ,A9 8M         MM YM.    ,            ‖")
                        print("‖             ''bmmmdPY   'Ybmd9'   'Ybmd9'   YMMMMMb .JMML.'Mbmmd'            ‖")
                        print("‖                                            6'     dP                         ‖")
                        print("‖                         NET SUCHMASCHINE    Ybmmmd'      ALPHA               ‖")
                        print("‖                                                                              ‖")
                        print("‖                                                                              ‖")
                        print("‖         NACHRICHTEN ╏ PROTESTE GEGEN AFD GESTARTET                           ‖")
                        print("‖                     ╏ PAPST LEO XIV VERREIST IN DIE TÜRKEI                   ‖")
                        print("‖                     ╏ DEUTSCHE SPENDEN WENIGER ALS IM VORJAHR (2024)         ‖")
                        print("‖                     ╏ IMMER MEHR DEUTSCHE SUCHEN RAT BEI KI                  ‖")
                        print("‖                                                                              ‖")
                        print("................................................................................")
                        print("Tut uns leid, die Google Such API wurde im Mai 2016 heruntergefahren.")
                        print("Bitte wählen sie zwischen gespeicherten Ergebnissen für:")
                        print("            [1] Bulletin Board System")
                        print("            [2] Apple II")
                        print("            [3] Commodore 64")
                        selec_google_result = input("")
                        if selec_google_result == "1":
                            os.system('cls' if os.name == 'nt' else 'clear')
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&      &&&&      &&&&      &&&&")
                            print("&&&&&*   &&&   &&   &&&&&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&&        &&&&&&   &&&&")
                            print("&&&&&*   &&&&&    #&&&&&&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&&      &&   &&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&   &&=      &&&   &&&&")
                            print("&&&&&*   &&   &&&&    &&&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&           +&&&   &&&&")
                            print("&&&&&&&&&&&&&&    &&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("Ihr Modem hat nicht mehr mit dem PC kommuniziert. Schauen sie nach, ob der Parallelanschluss locker ist.")
                            time.sleep(1)
                            print("ERR_KERNEL_PANIC")
                            os.system('shutdown -f' if os.name == 'nt' else 'systemctl poweroff')
                        elif selec_google_result == "2":
                            os.system('cls' if os.name == 'nt' else 'clear')
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&      &&&&      &&&&      &&&&")
                            print("&&&&&*   &&&   &&   &&&&&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&&        &&&&&&   &&&&")
                            print("&&&&&*   &&&&&    #&&&&&&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&&      &&   &&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&   &&=      &&&   &&&&")
                            print("&&&&&*   &&   &&&&    &&&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&           +&&&   &&&&")
                            print("&&&&&&&&&&&&&&    &&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("Ihr Modem hat nicht mehr mit dem PC kommuniziert. Schauen sie nach, ob der Parallelanschluss locker ist.")
                            time.sleep(1)
                            print("ERR_KERNEL_PANIC")
                            os.system('shutdown -f' if os.name == 'nt' else 'systemctl poweroff')
                        elif selec_google_result == "3":
                            os.system('cls' if os.name == 'nt' else 'clear')
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&      &&&&      &&&&      &&&&")
                            print("&&&&&*   &&&   &&   &&&&&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&&        &&&&&&   &&&&")
                            print("&&&&&*   &&&&&    #&&&&&&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&&      &&   &&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&   &&=      &&&   &&&&")
                            print("&&&&&*   &&   &&&&    &&&&   &&&&")
                            time.sleep(1)
                            print("&&&&&*   &&           +&&&   &&&&")
                            print("&&&&&&&&&&&&&&    &&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
                            time.sleep(1)
                            print("Ihr Modem hat nicht mehr mit dem PC kommuniziert. Schauen sie nach, ob der Parallelanschluss locker ist.")
                            time.sleep(1)
                            print("ERR_KERNEL_PANIC")
                            os.system('shutdown -f' if os.name == 'nt' else 'systemctl poweroff')
                    
        if action == "nichtgut":
            os.system('cls' if os.name == 'nt' else 'clear')
            time.sleep(1)
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            time.sleep(1)
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            time.sleep(1)
            print("&&&      &&&&      &&&&      &&&&")
            print("&&&&&*   &&&   &&   &&&&&&   &&&&")
            time.sleep(1)
            print("&&&&&*   &&&        &&&&&&   &&&&")
            print("&&&&&*   &&&&&    #&&&&&&&   &&&&")
            time.sleep(1)
            print("&&&&&*   &&&      &&   &&&   &&&&")
            time.sleep(1)
            print("&&&&&*   &&   &&=      &&&   &&&&")
            print("&&&&&*   &&   &&&&    &&&&   &&&&")
            time.sleep(1)
            print("&&&&&*   &&           +&&&   &&&&")
            print("&&&&&&&&&&&&&&    &&&&&&&&&&&&&&&")
            time.sleep(1)
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            time.sleep(1)
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            time.sleep(1)
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            time.sleep(1)
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            time.sleep(1)
            print("Das sieht gar nicht gut aus.")
            time.sleep(1)
            print("ERR_KERNEL_PANIC")
            os.system('shutdown -f' if os.name == 'nt' else 'systemctl poweroff')